package com.dityish.apratim2k16;


public interface SHARED_CONSTANTS {


    int [] HOME_BACK_PICS={R.drawable.home5,R.drawable.home2,R.drawable.home4,R.drawable.home3,R.drawable.home1};
    int [] HOME_BACK_COLORS={R.color.home5,R.color.home2,R.color.home4,R.color.home3,R.color.home1};


    String [] eventsNames = { "antakshri",
            "aqua_jet",
            "arm_wrestling",
            "basketball",
            "beach_football",
            "bhangra_wars",
            "bob_the_builder",
            "boltmania",
            "bridge_it",
            "call_of_duty",
            "caption_writing",
            "civil_wars",
            "code_mania",
            "collage_making",
            "counter_strike",
            "duet_dance",
            "electro_quiz",
            "english_conventional_debate",
            "face_painting",
            "fashion_show",
            "fifa16",
            "five_a_side_football",
            "folk_dance",
            "free_fliers",
            "fusion_band",
            "graffiti",
            "group_dance",
            "group_discussion",
            "hindi_conventional_debate",
            "jam_wars",
            "line_follower",
            "little_tales",
            "maze_solver",
            "minute_to_win_it",
            "mock_the_rock",
            "mr_and_ms_apratim",
            "nfs_most_wanted",
            "paint_ball",
            "photography",
            "quiz_fun",
            "quiz_literary",
            "rj_hunt",
            "robo_race",
            "robo_wars",
            "short_movie",
            "skit",
            "solo_dance",
            "solo_instrumental",
            "solo_singing",
            "sports_quiz",
            "stage_play",
            "street_dance",
            "street_play",
            "street_soccer",
            "tattoo_making",
            "tech_hunt",
            "treasure_hunt",
            "tshirt_designing",
            "tug_of_bots",
            "vivify",
            "webdroid",
            "inaguration",
            "cricket_tournament",
            "face_the_bull",
            "duet_finals",
            "solo_finals",
            "rangoli",
            "five_a_side_football_2nd",
            "basketball_2nd",
            "beach_football_2nd",
            "boltmania_2nd",
            "cricket_tournament_2nd",
            "mono_act",
            "solo_instrumental_final",
            "solo_singing_final",
            "debate_english_finals",
            "dance_on_dj",
            "lan_gaming_finals",
            "admad",
            "edm_nigh",
            "star_night"};

}
